routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('{locale?}')->name('locale.')->group(function (){
    //Main routes
    Route::get('','Main\IndexController@index')->name('home');

    //Global setting routes
    Route::post('/set-user', 'Main\GlobalController@setUser')->name('set-user');
    Route::post('/set-address', 'Main\GlobalController@getAddress')->name('get-address');
    Route::post('/update-basket-page', 'Main\GlobalController@updateBasketPage')->name('update-basket-page');

    //Order checkout
    Route::post('checkout', 'Main\OrderController@checkout')->name('checkout');

    //Mails
    Route::get('contact-us','Main\ContactUsController@index')->name('contact-us');
    Route::post('contact-us-send','Main\ContactUsController@send')->name('contact-us-send');

    //Pages
    Route::get('business-model','Main\SinglePagesController@businessModel')->name('business-model');
    Route::get('about-company','Main\SinglePagesController@aboutCompany')->name('about-company');
    Route::get('payment-orders','Main\SinglePagesController@paymentOrders')->name('payment-orders');
    Route::get('delivery-points','Main\SinglePagesController@deliveryPoints')->name('delivery-points');
    Route::get('terms-of-use','Main\SinglePagesController@termsOfUse')->name('terms-of-use');
    Route::get('confidentiality','Main\SinglePagesController@confidentiality')->name('confidentiality');

    //Catalog
    Route::prefix('/catalog/{name}')->name('catalog.')->group(function (){
        Route::get('','Main\CatalogController@index')->name('book');
        Route::post('get-page/{page}', 'Main\CatalogController@getPage')->name('get-page');
    });

    //Products
    Route::get('statuses/{prefix}','Main\ProductController@statuses')->name('statuses');
    Route::get('product/{articul__id}','Main\ProductController@product')->name('product');

    //Basket
    Route::prefix('/basket')->name('basket.')->group(function (){
        Route::get('','Main\BasketController@index')->name('index');
        Route::post('update', 'Main\BasketController@update')->name('update');
    });

    //Required user
    Route::middleware('user_middle')->group(function (){
        Route::prefix('/profile')->name('profile.')->group(function (){

            Route::post('/converse-post', 'Main\PaymentController@converse_post')->name('converse_post');
            Route::any('/converse-success', ['as'=>'converse_back_url', 
                'uses'=>'Main\PaymentController@back_url_conerse']);

            Route::any('','Main\ProfileController@index')->name('index');
            Route::get('orders','Main\ProfileController@orders')->name('orders');
            Route::get('edit','Main\ProfileController@edit')->name('edit');
            Route::post('update','Main\ProfileController@update')->name('update');
            Route::get('reports','Main\ProfileController@reports')->name('reports');
            Route::post('reports/export','Main\ProfileController@exportReport')->name('export-report');
            Route::get('logout','Main\ProfileController@logout')->name('logout');
            Route::post('get-product/{articul}', 'Main\ProfileController@getProduct')->name('get-product');
            Route::post('store-to-basket', 'Main\ProfileController@storeToBasket')->name('store-to-basket');
        });
    });

    //Required guest or admin
    Route::middleware('guest_middle')->group(function (){
        Route::get('registration','Main\RegistrationController@index')->name('registration');
        Route::post('registration-send','Main\RegistrationController@send')->name('registration-send');
        Route::get('registration-verify','Main\RegistrationController@verify')->name('registration-verify');
        Route::post('sign-in', 'Main\ProfileController@signIn')->name('sign-in');
    });

    //Admin routes
    Route::prefix('/admin')->name('admin.')->group(function (){
        Route::get('login','Admin\AuthController@login')->name('login');
        Route::post('sign','Admin\AuthController@sign')->name('sign');

        Route::middleware('auth_middle')->group(function (){
            Route::get('personal-details', 'Admin\IndexController@personalDetails')->name('personal-details');
            Route::post('update-admin','Admin\IndexController@updateAdmin')->name('update-admin');
            Route::post('redactor-image-upload','Admin\IndexController@redactorImageUpload')->name('redactor-image-upload');
            Route::get('logout','Admin\AuthController@logout')->name('logout');

            //Catalog
            Route::resource('catalog', 'Admin\CatalogController');
            Route::post('/catalog/{catalog}/activate','Admin\CatalogController@activate')->name('catalog.activate');

            //Pages
            Route::prefix('/catalog/{catalog}')->name('catalog.')->group(function (){
                Route::resource('page', 'Admin\PageController');
            });

            //Products
            Route::resource('product', 'Admin\ProductController');
            Route::post('/product/{product}/{image}/delete-image','Admin\ProductController@deleteImage')->name('product.delete-image');

            //Slider
            Route::resource('slider', 'Admin\SliderController');

            //Information
            Route::get('information', 'Admin\InformationController@index')->name('information.index');
            Route::get('information/{prefix}', 'Admin\InformationController@show')->name('information.show');
            Route::put('information/{prefix}/update', 'Admin\InformationController@update')->name('information.update');

            //Users
            Route::resource('users', 'Admin\UsersController');
            Route::post('users/{user}/verify', 'Admin\UsersController@verify')->name('users.verify');
            Route::post('users/{user}/block', 'Admin\UsersController@block')->name('users.block');
            Route::post('users/{user}/restore', 'Admin\UsersController@restore')->name('users.restore');

            //Orders
            Route::prefix('orders/{type}')->name('orders.')->group(function (){
                Route::get('', 'Admin\OrderController@index')->name('index');

                Route::prefix('{order_id}')->group(function (){
                    Route::get('products', 'Admin\OrderController@products')->name('products');

                    Route::post('finish', 'Admin\OrderController@finish')->name('finish');
                    Route::post('pay', 'Admin\OrderController@pay')->name('pay');
                    Route::post('{which}/{action}', 'Admin\OrderController@change')->name('change');
                });
            });

            //Report orders
            Route::get('report-orders', 'Admin\ReportController@orders')->name('report.orders');
            Route::post('report-orders-download', 'Admin\ReportController@ordersDownload')->name('report.orders.download');

            //Report products
            Route::get('report-products', 'Admin\ReportController@products')->name('report.products');
            Route::post('report-products-download', 'Admin\ReportController@productsDownload')->name('report.products.download');

            //Address
            Route::resource('address', 'Admin\AddressController');

            //Import
            Route::get('import', 'Admin\ImportController@index')->name('import.index');
            Route::post('importing', 'Admin\ImportController@importing')->name('import.importing');
        });
    });
});

Auth::routes();

resources/views/admin/page/create.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => trans('admin.add'),
                'icon' => 'plus'
            ],
            [
                'route' => route('locale.admin.catalog.page.index',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => trans('admin.pages'),
                'icon' => 'leanpub'
            ],
            [
                'route' => route('locale.admin.catalog.show',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => $catalog->name,
                'icon' => null
            ],
            [
                'route' => route('locale.admin.catalog.index',$locale['prefix']),
                'text' => trans('admin.catalogs'),
                'icon' => 'book'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-body create_body">
        @if ($errors->any())
            <ul class="alert alert-danger list_type_none">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        {!! Form::open(['url' => route('locale.admin.catalog.page.store',['locale' => $locale['prefix'], 'catalog' => $catalog->id]), 'class' => 'form-horizontal', 'files' => true]) !!}

        @include ('admin.page.form', ['formMode' => 'create'])

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/page/edit.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => trans('admin.edit'),
                'icon' => 'pencil'
            ],
            [
                'route' => route('locale.admin.catalog.page.show',['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $page->id]),
                'text' => $page->id,
                'icon' => null
            ],
            [
                'route' => route('locale.admin.catalog.page.index',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => trans('admin.pages'),
                'icon' => 'leanpub'
            ],
            [
                'route' => route('locale.admin.catalog.show',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => $catalog->name,
                'icon' => null
            ],
            [
                'route' => route('locale.admin.catalog.index',$locale['prefix']),
                'text' => trans('admin.catalogs'),
                'icon' => 'book'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-body edit_body">
        @if ($errors->any())
            <ul class="alert alert-danger list_type_none">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

       {!! Form::model($page, [
           'method' => 'PATCH',
           'url' => route('locale.admin.catalog.page.update',['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $page->id]),
           'class' => 'form-horizontal',
           'files' => true
       ]) !!}

       @include ('admin.page.form', ['formMode' => 'edit'])

       {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/page/form.blade.php
<div class="d-flex d-justify-center d-align-center">
    @include('admin.extensions.image',[
        'label' => trans('admin.image'),
        'name' => 'image',
        'path' => 'main/pages',
        'item' => $page ?? null
    ])
</div>

@include('admin.extensions.multiselect',[
    'label' => trans('admin.products'),
    'name' => 'products',
    'options' => $products,
    'selected_values' => isset($page) ? $page->products->pluck('id')->toArray() : [],
    'field' => 'title',
    'field_two' => 'articul',
    'translate' => true,
])

<div class="form-group text-right">
    {!! Form::submit($formMode === 'edit' ? trans('admin.update') : trans('admin.add'), ['class' => 'btn btn-success']) !!}
</div>

resources/views/admin/page/index.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => trans('admin.pages'),
                'icon' => 'leanpub'
            ],
            [
                'route' => route('locale.admin.catalog.show',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => $catalog->name,
                'icon' => null
            ],
            [
                'route' => route('locale.admin.catalog.index',$locale['prefix']),
                'text' => trans('admin.catalogs'),
                'icon' => 'book'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-header d-flex d-justify-between d-align-center">
        <div>
            <a href="{{ route('locale.admin.catalog.page.create',['locale' => $locale['prefix'], 'catalog' => $catalog->id]) }}" class="btn btn-success btn-sm">
                <i class="fa fa-plus" aria-hidden="true"></i> @lang('admin.add')
            </a>
        </div>
    </div>
    <div class="card-body index_body">
        <div class="table-responsive">
            <table class="table table-borderless">
                <thead>
                    <tr>
                        <th>#</th>
                        <th> @lang('admin.image') </th>
                        <th style="text-align: right">@lang('admin.actions')</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($pages as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td class="image_part" style="height: 350px!important">
                            <img src="{{ asset('main/pages/' . $item->image) }}" alt="">
                        </td>
                        <td style="text-align: right">
                            <a href="#">
                                <button class="btn btn-warning btn-sm" style="color: white">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    @lang('admin.products') ({{ $item->products_count }})
                                </button>
                            </a>
                            <a href="{{ route('locale.admin.catalog.page.show', ['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $item->id]) }}" title="View Page"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> @lang('admin.show')</button></a>
                            <a href="{{ route('locale.admin.catalog.page.edit', ['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $item->id]) }}" title="Edit Page"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('admin.edit')</button></a>
                            {!! Form::open([
                                'method'=>'DELETE',
                                'url' => route('locale.admin.catalog.page.destroy', ['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $item->id]),
                                'style' => 'display:inline',
                                'class' => 'delete_form'
                            ]) !!}
                            {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> ' . trans('admin.delete'), array(
                                'type' => 'button',
                                'class' => 'btn btn-danger btn-sm delete',
                            )) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="pagination-wrapper"> {!! $pages->render() !!} </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('body').on('click','.delete', function () {
                let form = $(this).parents('form.delete_form');
                swal({
                    title: trans('are_you_sure'),
                    text: trans('return_is_failed'),
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: trans('yes_delete'),
                    cancelButtonText: trans('cancel'),
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger m-l-10',
                    buttonsStyling: false,
                }).then(() => {
                    form.submit();
                }, (dismiss) => {
                    if (dismiss === 'cancel') {
                        swal({
                            title: trans('canceled'),
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }).catch(swal.noop);
                    }
                })
            })
        })
    </script>
@endsection

resources/views/admin/page/show.blade.php
@extends('layouts.admin')


@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => $page->id,
                'icon' => null
            ],
            [
                'route' => route('locale.admin.catalog.page.index',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => trans('admin.pages'),
                'icon' => 'leanpub'
            ],
            [
                'route' => route('locale.admin.catalog.show',['locale' => $locale['prefix'], 'catalog' => $catalog->id]),
                'text' => $catalog->name,
                'icon' => null
            ],
            [
                'route' => route('locale.admin.catalog.index',$locale['prefix']),
                'text' => trans('admin.catalogs'),
                'icon' => 'book'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-header">
        <a href="{{ route('locale.admin.catalog.page.edit', ['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $page->id]) }}" title="Edit Page">
            <button class="btn btn-primary btn-sm">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('admin.edit')
            </button>
        </a>

        {!! Form::open([
            'method'=>'DELETE',
            'url' => route('locale.admin.catalog.page.destroy', ['locale' => $locale['prefix'], 'catalog' => $catalog->id, 'page' => $page->id]),
            'style' => 'display:inline',
            'class' => 'delete_form'
        ]) !!}
        {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> ' . trans('admin.delete'), array(
            'type' => 'button',
            'class' => 'btn btn-danger btn-sm delete',
        )) !!}
        {!! Form::close() !!}
    </div>

    <div class="card-body show_body">
        <div class="table-responsive">
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <th>#</th>
                        <td>{{ $page->id }}</td>
                    </tr>
                    <tr>
                        <th> @lang('admin.image') </th>
                        <td>
                            <img src="{{ asset('main/pages/' . $page->image) }}" alt="">
                        </td>
                    </tr>
                    <tr>
                        <th> @lang('admin.products') ({{ count($page->products) }}) </th>
                        <td>
                            <ul style="margin: 0; padding:0; list-style-type: none">
                                @foreach($page->products as $product)
                                    <li>
                                        <a href="{{ route('locale.admin.product.show',['locale' => $locale['prefix'], 'product' => $product->id]) }}" class="d-flex d-align-center">
                                            <img src="{{ $product->topImage() }}" alt="" style="width: 50px; height: 50px">
                                            {{ $product->translate('title') }}
                                        </a>
                                    </li>
                                @endforeach
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th> @lang('admin.created_at') </th>
                        <td>{{ $page->created_at }}</td>
                    </tr>
                    <tr>
                        <th> @lang('admin.updated_at') </th>
                        <td>{{ $page->updated_at }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('body').on('click','.delete', function () {
                let form = $(this).parents('form.delete_form');
                swal({
                    title: trans('are_you_sure'),
                    text: trans('return_is_failed'),
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: trans('yes_delete'),
                    cancelButtonText: trans('cancel'),
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger m-l-10',
                    buttonsStyling: false,
                }).then(() => {
                    form.submit();
                }, (dismiss) => {
                    if (dismiss === 'cancel') {
                        swal({
                            title: trans('canceled'),
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }).catch(swal.noop);
                    }
                })
            })
        })
    </script>
@endsection