routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('{locale?}')->name('locale.')->group(function (){
    //Main routes
    Route::get('','Main\IndexController@index')->name('home');

    //Global setting routes
    Route::post('/set-user', 'Main\GlobalController@setUser')->name('set-user');
    Route::post('/set-address', 'Main\GlobalController@getAddress')->name('get-address');
    Route::post('/update-basket-page', 'Main\GlobalController@updateBasketPage')->name('update-basket-page');

    //Order checkout
    Route::post('checkout', 'Main\OrderController@checkout')->name('checkout');

    //Mails
    Route::get('contact-us','Main\ContactUsController@index')->name('contact-us');
    Route::post('contact-us-send','Main\ContactUsController@send')->name('contact-us-send');

    //Pages
    Route::get('business-model','Main\SinglePagesController@businessModel')->name('business-model');
    Route::get('about-company','Main\SinglePagesController@aboutCompany')->name('about-company');
    Route::get('payment-orders','Main\SinglePagesController@paymentOrders')->name('payment-orders');
    Route::get('delivery-points','Main\SinglePagesController@deliveryPoints')->name('delivery-points');
    Route::get('terms-of-use','Main\SinglePagesController@termsOfUse')->name('terms-of-use');
    Route::get('confidentiality','Main\SinglePagesController@confidentiality')->name('confidentiality');

    //Catalog
    Route::prefix('/catalog/{name}')->name('catalog.')->group(function (){
        Route::get('','Main\CatalogController@index')->name('book');
        Route::post('get-page/{page}', 'Main\CatalogController@getPage')->name('get-page');
    });

    //Products
    Route::get('statuses/{prefix}','Main\ProductController@statuses')->name('statuses');
    Route::get('product/{articul__id}','Main\ProductController@product')->name('product');

    //Basket
    Route::prefix('/basket')->name('basket.')->group(function (){
        Route::get('','Main\BasketController@index')->name('index');
        Route::post('update', 'Main\BasketController@update')->name('update');
    });

    //Required user
    Route::middleware('user_middle')->group(function (){
        Route::prefix('/profile')->name('profile.')->group(function (){

            Route::post('/converse-post', 'Main\PaymentController@converse_post')->name('converse_post');
            Route::any('/converse-success', ['as'=>'converse_back_url', 
                'uses'=>'Main\PaymentController@back_url_conerse']);

            Route::any('','Main\ProfileController@index')->name('index');
            Route::get('orders','Main\ProfileController@orders')->name('orders');
            Route::get('edit','Main\ProfileController@edit')->name('edit');
            Route::post('update','Main\ProfileController@update')->name('update');
            Route::get('reports','Main\ProfileController@reports')->name('reports');
            Route::post('reports/export','Main\ProfileController@exportReport')->name('export-report');
            Route::get('logout','Main\ProfileController@logout')->name('logout');
            Route::post('get-product/{articul}', 'Main\ProfileController@getProduct')->name('get-product');
            Route::post('store-to-basket', 'Main\ProfileController@storeToBasket')->name('store-to-basket');
        });
    });

    //Required guest or admin
    Route::middleware('guest_middle')->group(function (){
        Route::get('registration','Main\RegistrationController@index')->name('registration');
        Route::post('registration-send','Main\RegistrationController@send')->name('registration-send');
        Route::get('registration-verify','Main\RegistrationController@verify')->name('registration-verify');
        Route::post('sign-in', 'Main\ProfileController@signIn')->name('sign-in');
    });

    //Admin routes
    Route::prefix('/admin')->name('admin.')->group(function (){
        Route::get('login','Admin\AuthController@login')->name('login');
        Route::post('sign','Admin\AuthController@sign')->name('sign');

        Route::middleware('auth_middle')->group(function (){
            Route::get('personal-details', 'Admin\IndexController@personalDetails')->name('personal-details');
            Route::post('update-admin','Admin\IndexController@updateAdmin')->name('update-admin');
            Route::post('redactor-image-upload','Admin\IndexController@redactorImageUpload')->name('redactor-image-upload');
            Route::get('logout','Admin\AuthController@logout')->name('logout');

            //Catalog
            Route::resource('catalog', 'Admin\CatalogController');
            Route::post('/catalog/{catalog}/activate','Admin\CatalogController@activate')->name('catalog.activate');

            //Pages
            Route::prefix('/catalog/{catalog}')->name('catalog.')->group(function (){
                Route::resource('page', 'Admin\PageController');
            });

            //Products
            Route::resource('product', 'Admin\ProductController');
            Route::post('/product/{product}/{image}/delete-image','Admin\ProductController@deleteImage')->name('product.delete-image');

            //Slider
            Route::resource('slider', 'Admin\SliderController');

            //Information
            Route::get('information', 'Admin\InformationController@index')->name('information.index');
            Route::get('information/{prefix}', 'Admin\InformationController@show')->name('information.show');
            Route::put('information/{prefix}/update', 'Admin\InformationController@update')->name('information.update');

            //Users
            Route::resource('users', 'Admin\UsersController');
            Route::post('users/{user}/verify', 'Admin\UsersController@verify')->name('users.verify');
            Route::post('users/{user}/block', 'Admin\UsersController@block')->name('users.block');
            Route::post('users/{user}/restore', 'Admin\UsersController@restore')->name('users.restore');

            //Orders
            Route::prefix('orders/{type}')->name('orders.')->group(function (){
                Route::get('', 'Admin\OrderController@index')->name('index');

                Route::prefix('{order_id}')->group(function (){
                    Route::get('products', 'Admin\OrderController@products')->name('products');

                    Route::post('finish', 'Admin\OrderController@finish')->name('finish');
                    Route::post('pay', 'Admin\OrderController@pay')->name('pay');
                    Route::post('{which}/{action}', 'Admin\OrderController@change')->name('change');
                });
            });

            //Report orders
            Route::get('report-orders', 'Admin\ReportController@orders')->name('report.orders');
            Route::post('report-orders-download', 'Admin\ReportController@ordersDownload')->name('report.orders.download');

            //Report products
            Route::get('report-products', 'Admin\ReportController@products')->name('report.products');
            Route::post('report-products-download', 'Admin\ReportController@productsDownload')->name('report.products.download');

            //Address
            Route::resource('address', 'Admin\AddressController');

            //Import
            Route::get('import', 'Admin\ImportController@index')->name('import.index');
            Route::post('importing', 'Admin\ImportController@importing')->name('import.importing');
        });
    });
});

Auth::routes();

resources/views/admin/login.blade.php
<!doctype html>
<html lang="{{ $locale['prefix'] }}">
<head>
    <meta charset="utf-8"/>
    <link rel="apple-touch-icon" sizes="76x76" href="http://www.urbanui.com/"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>@lang('admin.login')</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width"/>
    <link href="{{ asset('dashboard/assets/css/bootstrap.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('dashboard/assets/css/turbo.css') }}" rel="stylesheet"/>
    <link href="{{ asset('dashboard/assets/css/demo.css') }}" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons"/>
    <link rel="icon" href="{{ asset('main/img/icon/logo.ico') }}" type="ico" sizes="16x16">
</head>

<body>
<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" data-color="blue">
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        <form method="post" action="{{ route('locale.admin.sign',$locale['prefix']) }}">
                            @csrf
                            <div class="card card-login card-hidden">
                                <div class="card-header text-center">
                                    <h4 class="card-title">@lang('admin.login')</h4>
                                </div>
                                <div class="card-content">
                                    @if(session()->has('invalid_admin'))
                                        <h5 class="c-red text-center">@lang('admin.invalid_admin')</h5>
                                    @endif
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">face</i>
                                        </span>
                                        <div class="form-group label-floating">
                                            <label class="control-label">@lang('admin.name')</label>
                                            <input name="email" type="text" class="form-control" value="{{ old('email') }}">
                                        </div>
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">lock_outline</i>
                                        </span>
                                        <div class="form-group label-floating">
                                            <label class="control-label">@lang('admin.password')</label>
                                            <input name="password" type="password" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-wd btn-md btn-success">@lang('admin.sign_in')</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<script src="{{ asset('dashboard/assets/vendors/jquery-3.1.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/material.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.validate.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/moment.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/chartist.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap-notify.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery-jvectormap.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/nouislider.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.tagsinput.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/turbo.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/demo.js') }}"></script>

<script type="text/javascript">
    $().ready(function () {
        demo.checkFullPageBackgroundImage();
        setTimeout(function () {
            $('.card').removeClass('card-hidden');
        }, 700)
    });
</script>
</html>

resources/views/admin/personal-details.blade.php
@extends('layouts.admin')

@section('content')
    <div class="card-body create_body">
        @if ($errors->any())
            <ul class="alert alert-danger list_type_none">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        @if(session()->has('password_error'))
            <ul class="alert alert-danger list_type_none">
                <li>{{ session()->get('password_error') }}</li>
            </ul>
        @endif

        <form method="post" class="form-horizontal" action="{{ route('locale.admin.update-admin',$locale['prefix']) }}">
            @csrf
            <div class="form-group">
                <label for="email" class="control-label">@lang('admin.name')</label>
                <input disabled type="text" id="email" value="{{ Auth::user()->email }}" class="form-control">
            </div>
            <div class="form-group">
                <label for="new_password" class="control-label">@lang('admin.new_password')</label>
                <input type="password" name="new_password" id="new_password" class="form-control">
            </div>
            <div class="form-group">
                <label for="retry_password" class="control-label">@lang('admin.retry_password')</label>
                <input type="password" name="retry_password" id="retry_password" class="form-control">
            </div>
            <div class="form-group">
                <label for="current_password" class="control-label">@lang('admin.current_password')</label>
                <input type="password" name="current_password" id="current_password" class="form-control">
            </div>
            <div class="form-group text-right">
                <input type="submit" class="btn btn-success" value="@lang('admin.update')">
            </div>
        </form>
    </div>
@endsection