routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('{locale?}')->name('locale.')->group(function (){
    //Main routes
    Route::get('','Main\IndexController@index')->name('home');

    //Global setting routes
    Route::post('/set-user', 'Main\GlobalController@setUser')->name('set-user');
    Route::post('/set-address', 'Main\GlobalController@getAddress')->name('get-address');
    Route::post('/update-basket-page', 'Main\GlobalController@updateBasketPage')->name('update-basket-page');

    //Order checkout
    Route::post('checkout', 'Main\OrderController@checkout')->name('checkout');

    //Mails
    Route::get('contact-us','Main\ContactUsController@index')->name('contact-us');
    Route::post('contact-us-send','Main\ContactUsController@send')->name('contact-us-send');

    //Pages
    Route::get('business-model','Main\SinglePagesController@businessModel')->name('business-model');
    Route::get('about-company','Main\SinglePagesController@aboutCompany')->name('about-company');
    Route::get('payment-orders','Main\SinglePagesController@paymentOrders')->name('payment-orders');
    Route::get('delivery-points','Main\SinglePagesController@deliveryPoints')->name('delivery-points');
    Route::get('terms-of-use','Main\SinglePagesController@termsOfUse')->name('terms-of-use');
    Route::get('confidentiality','Main\SinglePagesController@confidentiality')->name('confidentiality');

    //Catalog
    Route::prefix('/catalog/{name}')->name('catalog.')->group(function (){
        Route::get('','Main\CatalogController@index')->name('book');
        Route::post('get-page/{page}', 'Main\CatalogController@getPage')->name('get-page');
    });

    //Products
    Route::get('statuses/{prefix}','Main\ProductController@statuses')->name('statuses');
    Route::get('product/{articul__id}','Main\ProductController@product')->name('product');

    //Basket
    Route::prefix('/basket')->name('basket.')->group(function (){
        Route::get('','Main\BasketController@index')->name('index');
        Route::post('update', 'Main\BasketController@update')->name('update');
    });

    //Required user
    Route::middleware('user_middle')->group(function (){
        Route::prefix('/profile')->name('profile.')->group(function (){

            Route::post('/converse-post', 'Main\PaymentController@converse_post')->name('converse_post');
            Route::any('/converse-success', ['as'=>'converse_back_url', 
                'uses'=>'Main\PaymentController@back_url_conerse']);

            Route::any('','Main\ProfileController@index')->name('index');
            Route::get('orders','Main\ProfileController@orders')->name('orders');
            Route::get('edit','Main\ProfileController@edit')->name('edit');
            Route::post('update','Main\ProfileController@update')->name('update');
            Route::get('reports','Main\ProfileController@reports')->name('reports');
            Route::post('reports/export','Main\ProfileController@exportReport')->name('export-report');
            Route::get('logout','Main\ProfileController@logout')->name('logout');
            Route::post('get-product/{articul}', 'Main\ProfileController@getProduct')->name('get-product');
            Route::post('store-to-basket', 'Main\ProfileController@storeToBasket')->name('store-to-basket');
        });
    });

    //Required guest or admin
    Route::middleware('guest_middle')->group(function (){
        Route::get('registration','Main\RegistrationController@index')->name('registration');
        Route::post('registration-send','Main\RegistrationController@send')->name('registration-send');
        Route::get('registration-verify','Main\RegistrationController@verify')->name('registration-verify');
        Route::post('sign-in', 'Main\ProfileController@signIn')->name('sign-in');
    });

    //Admin routes
    Route::prefix('/admin')->name('admin.')->group(function (){
        Route::get('login','Admin\AuthController@login')->name('login');
        Route::post('sign','Admin\AuthController@sign')->name('sign');

        Route::middleware('auth_middle')->group(function (){
            Route::get('personal-details', 'Admin\IndexController@personalDetails')->name('personal-details');
            Route::post('update-admin','Admin\IndexController@updateAdmin')->name('update-admin');
            Route::post('redactor-image-upload','Admin\IndexController@redactorImageUpload')->name('redactor-image-upload');
            Route::get('logout','Admin\AuthController@logout')->name('logout');

            //Catalog
            Route::resource('catalog', 'Admin\CatalogController');
            Route::post('/catalog/{catalog}/activate','Admin\CatalogController@activate')->name('catalog.activate');

            //Pages
            Route::prefix('/catalog/{catalog}')->name('catalog.')->group(function (){
                Route::resource('page', 'Admin\PageController');
            });

            //Products
            Route::resource('product', 'Admin\ProductController');
            Route::post('/product/{product}/{image}/delete-image','Admin\ProductController@deleteImage')->name('product.delete-image');

            //Slider
            Route::resource('slider', 'Admin\SliderController');

            //Information
            Route::get('information', 'Admin\InformationController@index')->name('information.index');
            Route::get('information/{prefix}', 'Admin\InformationController@show')->name('information.show');
            Route::put('information/{prefix}/update', 'Admin\InformationController@update')->name('information.update');

            //Users
            Route::resource('users', 'Admin\UsersController');
            Route::post('users/{user}/verify', 'Admin\UsersController@verify')->name('users.verify');
            Route::post('users/{user}/block', 'Admin\UsersController@block')->name('users.block');
            Route::post('users/{user}/restore', 'Admin\UsersController@restore')->name('users.restore');

            //Orders
            Route::prefix('orders/{type}')->name('orders.')->group(function (){
                Route::get('', 'Admin\OrderController@index')->name('index');

                Route::prefix('{order_id}')->group(function (){
                    Route::get('products', 'Admin\OrderController@products')->name('products');

                    Route::post('finish', 'Admin\OrderController@finish')->name('finish');
                    Route::post('pay', 'Admin\OrderController@pay')->name('pay');
                    Route::post('{which}/{action}', 'Admin\OrderController@change')->name('change');
                });
            });

            //Report orders
            Route::get('report-orders', 'Admin\ReportController@orders')->name('report.orders');
            Route::post('report-orders-download', 'Admin\ReportController@ordersDownload')->name('report.orders.download');

            //Report products
            Route::get('report-products', 'Admin\ReportController@products')->name('report.products');
            Route::post('report-products-download', 'Admin\ReportController@productsDownload')->name('report.products.download');

            //Address
            Route::resource('address', 'Admin\AddressController');

            //Import
            Route::get('import', 'Admin\ImportController@index')->name('import.index');
            Route::post('importing', 'Admin\ImportController@importing')->name('import.importing');
        });
    });
});

Auth::routes();

app/Http/Controllers/Admin/AddressController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Address;
use App\Models\AddressTranslations;
use App\Traits\CrudActions;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class AddressController extends Controller
{
    use CrudActions;

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $addresses = Address::query()->whereHas('translates', function($q) use($keyword){
                return $q->where('title', 'LIKE', "%$keyword%");
            })->latest()->paginate($perPage);
        } else {
            $addresses = Address::query()->latest()->paginate($perPage);
        }

        return view('admin.address.index', compact('addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('admin.address.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @param $locale
     * @return RedirectResponse|Redirector
     */
    public function store(Request $request,$locale)
    {
        $values = $request->get($this->default['prefix']);
        $values['percent'] = floatval($request->get('percent'));
        $values['embed'] = $request->get('embed');

        $rules = [
            'title' => 'required|max:255',
            'percent' => 'required|min:0',
            'embed' => 'required',
        ];

        $validate = Validator::make($values,$rules);
        if ($validate->fails()){
            return redirect()->back()->withErrors($validate)->withInput($request->input());
        }

        $address = new Address();
        $address->percent = $values['percent'];
        $address->embed = $values['embed'];
        $address->save();

        $insertData = $this->getOnlyFullTranslations($request->all(),'address_id',$address->id);
        AddressTranslations::query()->insert($insertData);

        return redirect(route('locale.admin.address.index',$locale))->with('sweet_alert', 'added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @param  int  $locale
     *
     * @return View
     */
    public function show($locale,$id)
    {
        $address = Address::query()->findOrFail($id);

        return view('admin.address.show', compact('address'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @param  int  $locale
     *
     * @return View
     */
    public function edit($locale,$id)
    {
        $address = Address::query()->findOrFail($id);

        return view('admin.address.edit', compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param $locale
     * @param int $id
     *
     * @return RedirectResponse|Redirector
     */
    public function update(Request $request, $locale, $id)
    {
        $address = Address::query()->findOrFail($id);

        $values = $request->get($this->default['prefix']);
        $values['percent'] = floatval($request->get('percent'));
        $values['embed'] = $request->get('embed');

        $rules = [
            'title' => 'required|max:255',
            'percent' => 'required|min:0',
            'embed' => 'required',
        ];

        $validate = Validator::make($values,$rules);
        if ($validate->fails()){
            return redirect()->back()->withErrors($validate)->withInput($request->input());
        }

        $address->percent = $values['percent'];
        $address->embed = $values['embed'];
        $address->save();

        $insertData = $this->getOnlyFullTranslations($request->all(),'address_id',$address->id);
        AddressTranslations::query()->where('address_id', $address->id)->delete();
        AddressTranslations::query()->insert($insertData);

        return redirect(route('locale.admin.address.index',$locale))->with('sweet_alert', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $locale
     * @param int $id
     *
     * @return RedirectResponse|Redirector
     */
    public function destroy($locale, $id)
    {
        Address::destroy($id);

        return redirect(route('locale.admin.address.index',$locale))->with('sweet_alert', 'deleted');
    }
}

resources/views/admin/address/create.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => trans('admin.add'),
                'icon' => 'plus'
            ],
            [
                'route' => route('locale.admin.address.index',$locale['prefix']),
                'text' => trans('admin.address'),
                'icon' => 'map-pin'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-body create_body">
        @if ($errors->any())
            <ul class="alert alert-danger list_type_none">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        {!! Form::open(['url' => route('locale.admin.address.store',$locale['prefix']), 'class' => 'form-horizontal', 'files' => true]) !!}

        @include ('admin.address.form', ['formMode' => 'create'])

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/address/edit.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => trans('admin.edit'),
                'icon' => 'pencil'
            ],
            [
                'route' => route('locale.admin.address.show',['locale' => $locale['prefix'], 'address' => $address->id]),
                'text' => $address->translate('title'),
                'icon' => null
            ],
            [
                'route' => route('locale.admin.address.index',$locale['prefix']),
                'text' => trans('admin.address'),
                'icon' => 'map-pin'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-body edit_body">
        @if ($errors->any())
            <ul class="alert alert-danger list_type_none">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

       {!! Form::model($address, [
           'method' => 'PATCH',
           'url' => route('locale.admin.address.update',['locale' => $locale['prefix'], 'address' => $address->id]),
           'class' => 'form-horizontal',
           'files' => true
       ]) !!}

       @include ('admin.address.form', ['formMode' => 'edit'])

       {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/address/form.blade.php
<div class="form-group {{ $errors->has('percent') ? 'has-error' : ''}}">
    {!! Form::label('percent', trans('admin.percent'), ['class' => 'control-label']) !!}
    {!! Form::text('percent', old('percent') ?? $address->percent ?? null, ['class' => 'form-control']) !!}
</div>

<div class="form-group {{ $errors->has('embed') ? 'has-error' : ''}}">
    {!! Form::label('embed', 'Embed', ['class' => 'control-label']) !!}
    {!! Form::text('embed', old('embed') ?? $address->embed ?? null, ['class' => 'form-control']) !!}
</div>

@include('admin.extensions.language',[
    'fields' => [
        [
            'label' => trans('admin.title'),
            'name' => 'title',
            'type' => 'text',
        ],
    ],
    'item' => $address ?? null,
])

<div class="form-group text-right">
    {!! Form::submit($formMode === 'edit' ? trans('admin.update') : trans('admin.add'), ['class' => 'btn btn-success']) !!}
</div>

resources/views/admin/address/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="card-header d-flex d-justify-between d-align-center">
        <div>
            <a href="{{ route('locale.admin.address.create',$locale['prefix']) }}" class="btn btn-success btn-sm">
                <i class="fa fa-plus" aria-hidden="true"></i> @lang('admin.add')
            </a>
        </div>
        <div>
            {!! Form::open(['method' => 'GET', 'url' => route('locale.admin.address.index', $locale['prefix']), 'class' => 'form-inline', 'role' => 'search'])  !!}
            <div class="input-group">
                <input type="text" class="form-control" name="search" placeholder="@lang('admin.title')..." value="{{ request('search') }}">
                <span class="input-group-append">
                    <button class="btn btn-warning" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                     @if(request()->has('search'))
                        <a class="btn btn-warning" href="{{ route('locale.admin.address.index',$locale['prefix']) }}">
                            <i class="fa fa-remove"></i>
                        </a>
                    @endif
                </span>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
    <div class="card-body index_body">
        <div class="table-responsive">
            <table class="table table-borderless">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>@lang('admin.title')</th>
                        <th>@lang('admin.percent')</th>
                        <th style="text-align: right">@lang('admin.actions')</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($addresses as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->translate('title') }}</td>
                        <td>{{ $item->percent }}</td>
                        <td style="text-align: right">
                            <a href="{{ route('locale.admin.address.show',['locale' => $locale['prefix'], 'address' => $item->id]) }}" title="View Address"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> @lang('admin.show')</button></a>
                            <a href="{{ route('locale.admin.address.edit',['locale' => $locale['prefix'], 'address' => $item->id]) }}" title="Edit Address"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('admin.edit')</button></a>
                            @if(count($addresses) > 1)
                                {!! Form::open([
                                   'method'=>'DELETE',
                                   'url' => route('locale.admin.address.destroy',['locale' => $locale['prefix'], 'address' => $item->id]),
                                   'style' => 'display:inline',
                                   'class' => 'delete_form'
                               ]) !!}
                                {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> ' . trans('admin.delete'), array(
                                    'type' => 'button',
                                    'class' => 'btn btn-danger btn-sm delete',
                                )) !!}
                                {!! Form::close() !!}
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="pagination-wrapper"> {!! $addresses->appends(['search' => Request::get('search')])->render() !!} </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('body').on('click','.delete', function () {
                let form = $(this).parents('form.delete_form');
                swal({
                    title: trans('are_you_sure'),
                    text: trans('return_is_failed'),
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: trans('yes_delete'),
                    cancelButtonText: trans('cancel'),
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger m-l-10',
                    buttonsStyling: false,
                }).then(() => {
                    form.submit();
                }, (dismiss) => {
                    if (dismiss === 'cancel') {
                        swal({
                            title: trans('canceled'),
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }).catch(swal.noop);
                    }
                })
            })
        })
    </script>
@endsection

resources/views/admin/address/show.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    @include('admin.extensions.breadcrumb', [
        'breadcrumbs' => [
            [
                'route' => null,
                'text' => $address->translate('title'),
                'icon' => 'eye'
            ],
            [
                'route' => route('locale.admin.address.index',$locale['prefix']),
                'text' => trans('admin.address'),
                'icon' => 'map-pin'
            ],
        ],
    ])
@endsection

@section('content')
    <div class="card-header">
        <a href="{{ route('locale.admin.address.edit',['locale' => $locale['prefix'], 'address' => $address->id]) }}" title="Edit Address">
            <button class="btn btn-primary btn-sm">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('admin.edit')
            </button>
        </a>
    </div>

    <div class="card-body show_body">
        <div class="table-responsive">
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <th>#</th>
                        <td>{{ $address->id }}</td>
                    </tr>
                    <tr>
                        <th> @lang('admin.title') </th>
                        <td>{{ $address->translate('title') }}</td>
                    </tr>
                    <tr>
                        <th> @lang('admin.percent') </th>
                        <td>{{ $address->percent }}</td>
                    </tr>
                    <tr>
                        <th> Embed </th>
                        <td>{{ $address->embed }}</td>
                    </tr>
                    <tr>
                        <th> @lang('admin.created_at') </th>
                        <td>{{ $address->created_at }}</td>
                    </tr>
                    <tr>
                        <th> @lang('admin.updated_at') </th>
                        <td>{{ $address->updated_at }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('body').on('click','.delete', function () {
                let form = $(this).parents('form.delete_form');
                swal({
                    title: trans('are_you_sure'),
                    text: trans('return_is_failed'),
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: trans('yes_delete'),
                    cancelButtonText: trans('cancel'),
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger m-l-10',
                    buttonsStyling: false,
                }).then(() => {
                    form.submit();
                }, (dismiss) => {
                    if (dismiss === 'cancel') {
                        swal({
                            title: trans('canceled'),
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }).catch(swal.noop);
                    }
                })
            })
        })
    </script>
@endsection