routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('{locale?}')->name('locale.')->group(function (){
    //Main routes
    Route::get('','Main\IndexController@index')->name('home');

    //Global setting routes
    Route::post('/set-user', 'Main\GlobalController@setUser')->name('set-user');
    Route::post('/set-address', 'Main\GlobalController@getAddress')->name('get-address');
    Route::post('/update-basket-page', 'Main\GlobalController@updateBasketPage')->name('update-basket-page');

    //Order checkout
    Route::post('checkout', 'Main\OrderController@checkout')->name('checkout');

    //Mails
    Route::get('contact-us','Main\ContactUsController@index')->name('contact-us');
    Route::post('contact-us-send','Main\ContactUsController@send')->name('contact-us-send');

    //Pages
    Route::get('business-model','Main\SinglePagesController@businessModel')->name('business-model');
    Route::get('about-company','Main\SinglePagesController@aboutCompany')->name('about-company');
    Route::get('payment-orders','Main\SinglePagesController@paymentOrders')->name('payment-orders');
    Route::get('delivery-points','Main\SinglePagesController@deliveryPoints')->name('delivery-points');
    Route::get('terms-of-use','Main\SinglePagesController@termsOfUse')->name('terms-of-use');
    Route::get('confidentiality','Main\SinglePagesController@confidentiality')->name('confidentiality');

    //Catalog
    Route::prefix('/catalog/{name}')->name('catalog.')->group(function (){
        Route::get('','Main\CatalogController@index')->name('book');
        Route::post('get-page/{page}', 'Main\CatalogController@getPage')->name('get-page');
    });

    //Products
    Route::get('statuses/{prefix}','Main\ProductController@statuses')->name('statuses');
    Route::get('product/{articul__id}','Main\ProductController@product')->name('product');

    //Basket
    Route::prefix('/basket')->name('basket.')->group(function (){
        Route::get('','Main\BasketController@index')->name('index');
        Route::post('update', 'Main\BasketController@update')->name('update');
    });

    //Required user
    Route::middleware('user_middle')->group(function (){
        Route::prefix('/profile')->name('profile.')->group(function (){

            Route::post('/converse-post', 'Main\PaymentController@converse_post')->name('converse_post');
            Route::any('/converse-success', ['as'=>'converse_back_url', 
                'uses'=>'Main\PaymentController@back_url_conerse']);

            Route::any('','Main\ProfileController@index')->name('index');
            Route::get('orders','Main\ProfileController@orders')->name('orders');
            Route::get('edit','Main\ProfileController@edit')->name('edit');
            Route::post('update','Main\ProfileController@update')->name('update');
            Route::get('reports','Main\ProfileController@reports')->name('reports');
            Route::post('reports/export','Main\ProfileController@exportReport')->name('export-report');
            Route::get('logout','Main\ProfileController@logout')->name('logout');
            Route::post('get-product/{articul}', 'Main\ProfileController@getProduct')->name('get-product');
            Route::post('store-to-basket', 'Main\ProfileController@storeToBasket')->name('store-to-basket');
        });
    });

    //Required guest or admin
    Route::middleware('guest_middle')->group(function (){
        Route::get('registration','Main\RegistrationController@index')->name('registration');
        Route::post('registration-send','Main\RegistrationController@send')->name('registration-send');
        Route::get('registration-verify','Main\RegistrationController@verify')->name('registration-verify');
        Route::post('sign-in', 'Main\ProfileController@signIn')->name('sign-in');
    });

    //Admin routes
    Route::prefix('/admin')->name('admin.')->group(function (){
        Route::get('login','Admin\AuthController@login')->name('login');
        Route::post('sign','Admin\AuthController@sign')->name('sign');

        Route::middleware('auth_middle')->group(function (){
            Route::get('personal-details', 'Admin\IndexController@personalDetails')->name('personal-details');
            Route::post('update-admin','Admin\IndexController@updateAdmin')->name('update-admin');
            Route::post('redactor-image-upload','Admin\IndexController@redactorImageUpload')->name('redactor-image-upload');
            Route::get('logout','Admin\AuthController@logout')->name('logout');

            //Catalog
            Route::resource('catalog', 'Admin\CatalogController');
            Route::post('/catalog/{catalog}/activate','Admin\CatalogController@activate')->name('catalog.activate');

            //Pages
            Route::prefix('/catalog/{catalog}')->name('catalog.')->group(function (){
                Route::resource('page', 'Admin\PageController');
            });

            //Products
            Route::resource('product', 'Admin\ProductController');
            Route::post('/product/{product}/{image}/delete-image','Admin\ProductController@deleteImage')->name('product.delete-image');

            //Slider
            Route::resource('slider', 'Admin\SliderController');

            //Information
            Route::get('information', 'Admin\InformationController@index')->name('information.index');
            Route::get('information/{prefix}', 'Admin\InformationController@show')->name('information.show');
            Route::put('information/{prefix}/update', 'Admin\InformationController@update')->name('information.update');

            //Users
            Route::resource('users', 'Admin\UsersController');
            Route::post('users/{user}/verify', 'Admin\UsersController@verify')->name('users.verify');
            Route::post('users/{user}/block', 'Admin\UsersController@block')->name('users.block');
            Route::post('users/{user}/restore', 'Admin\UsersController@restore')->name('users.restore');

            //Orders
            Route::prefix('orders/{type}')->name('orders.')->group(function (){
                Route::get('', 'Admin\OrderController@index')->name('index');

                Route::prefix('{order_id}')->group(function (){
                    Route::get('products', 'Admin\OrderController@products')->name('products');

                    Route::post('finish', 'Admin\OrderController@finish')->name('finish');
                    Route::post('pay', 'Admin\OrderController@pay')->name('pay');
                    Route::post('{which}/{action}', 'Admin\OrderController@change')->name('change');
                });
            });

            //Report orders
            Route::get('report-orders', 'Admin\ReportController@orders')->name('report.orders');
            Route::post('report-orders-download', 'Admin\ReportController@ordersDownload')->name('report.orders.download');

            //Report products
            Route::get('report-products', 'Admin\ReportController@products')->name('report.products');
            Route::post('report-products-download', 'Admin\ReportController@productsDownload')->name('report.products.download');

            //Address
            Route::resource('address', 'Admin\AddressController');

            //Import
            Route::get('import', 'Admin\ImportController@index')->name('import.index');
            Route::post('importing', 'Admin\ImportController@importing')->name('import.importing');
        });
    });
});

Auth::routes();

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\Models\Product;
use App\Models\ProductImages;
use App\Models\ProductStatuses;
use App\Models\ProductTranslations;
use App\Models\Status;
use App\Traits\CrudActions;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\View\View;

class ProductController extends Controller
{
    use CrudActions;

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $products = Product::query()->where('articul', 'LIKE', "%$keyword%")->with('images')->latest()->paginate($perPage);
        } else {
            $products = Product::query()->with('images')->latest()->paginate($perPage);
        }

        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        $statuses = Status::all();
        return view('admin.product.create', compact('statuses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @param $locale
     * @return RedirectResponse|Redirector
     */
    public function store(Request $request,$locale)
    {
        $requestData = $this->cleanFloara($request->all(),['description', 'composition']);
        $values = $requestData[$this->default['prefix']];
        $values['slug'] = Str::slug($values['title']);
        $values['articul'] = $requestData['articul'];
        $values['price'] = $requestData['price'];
        $values['discount'] = $requestData['discount'];
        $values['discount_for_more'] = $requestData['discount_for_more'];
        $values['easy_start'] = $requestData['easy_start'] ?? false ? true : false;
        $values['easy_start_price'] = $values['easy_start'] ? $requestData['easy_start_price'] : 0;
        $values['easy_start_step'] = $values['easy_start'] ? $requestData['easy_start_step'] : 0;
        $values['not_discount'] = $requestData['not_discount'] ?? false ? true : false;
        $values['statuses'] = $requestData['statuses'] ?? [];
        $values['product_images'] = $this->getOnlyValidImages($requestData['product_images'] ?? []);

        $rules = [
            'articul' => 'required|max:255',
            'title' => 'required|max:255',
        ];

        $validate = Validator::make($values,$rules);
        if ($validate->fails()){
            return redirect()->back()->withErrors($validate)->withInput($request->input());
        }

        $product = new Product();
        $product->slug = $values['slug'];
        $product->articul = (int)$values['articul'];
        $product->price = (int)$values['price'];
        $product->discount = (int)$values['discount'];
        $product->discount_for_more = (int)$values['discount_for_more'];
        $product->easy_start = (boolean)$values['easy_start'];
        $product->easy_start_price = (int)$values['easy_start_price'];
        $product->easy_start_step = (int)$values['easy_start_step'];
        $product->not_discount = (boolean)$values['not_discount'];
        $product->save();

        //Insert translations
        $insertData = $this->getOnlyFullTranslations($requestData,'product_id', $product->id, ['description','composition']);
        ProductTranslations::query()->insert($insertData);

        //Insert images
        if (count($values['product_images']) > 0){
            $insertImages = [];
            foreach ($values['product_images'] as $product_image){
                $image_path = time() . $product_image->getClientOriginalName();
                $product_image->move('main/products',$image_path);
                array_push($insertImages,[
                    'product_id' => $product->id,
                    'image' => $image_path
                ]);
            }
            ProductImages::query()->insert($insertImages);
        }

        //Insert statuses
        if (count($values['statuses']) > 0) {
            $insertStatuses = [];
            foreach ($values['statuses'] as $status_id){
                array_push($insertStatuses,[
                    'product_id' => $product->id,
                    'status_id' => $status_id
                ]);
            }
            ProductStatuses::query()->insert($insertStatuses);
        }

        return redirect(route('locale.admin.product.index',$locale))->with('sweet_alert', 'added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @param  string  $locale
     *
     * @return View
     */
    public function show($locale,$id)
    {
        $product = Product::query()->with('images', 'statuses')->findOrFail($id);

        return view('admin.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @param  string  $locale
     *
     * @return View
     */
    public function edit($locale,$id)
    {
        $product = Product::query()->with('images', 'statuses')->findOrFail($id);
        $statuses = Status::all();

        return view('admin.product.edit', compact('product', 'statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param $locale
     * @param int $id
     *
     * @return RedirectResponse|Redirector
     */
    public function update(Request $request, $locale, $id)
    {
        $product = Product::query()->with('images')->find($id);

        $requestData = $this->cleanFloara($request->all(),['description', 'composition']);
        $values = $requestData[$this->default['prefix']];
        $values['slug'] = Str::slug($values['title']);
        $values['articul'] = $requestData['articul'];
        $values['price'] = $requestData['price'];
        $values['discount'] = $requestData['discount'];
        $values['discount_for_more'] = $requestData['discount_for_more'];
        $values['easy_start'] = $requestData['easy_start'] ?? false ? true : false;
        $values['easy_start_price'] = $values['easy_start'] ? $requestData['easy_start_price'] : 0;
        $values['easy_start_step'] = $values['easy_start'] ? $requestData['easy_start_step'] : 0;
        $values['not_discount'] = $requestData['not_discount'] ?? false ? true : false;
        $values['product_images'] = $this->getOnlyValidImages($requestData['product_images'] ?? []);
        $values['statuses'] = $requestData['statuses'] ?? [];

        $rules = [
            'articul' => 'required|max:255',
            'title' => 'required|max:255',
        ];

        $validate = Validator::make($values,$rules);
        if ($validate->fails()){
            return redirect()->back()->withErrors($validate)->withInput($request->input());
        }

        $product->slug = $values['slug'];
        $product->articul = (int)$values['articul'];
        $product->price = (int)$values['price'];
        $product->discount = (int)$values['discount'];
        $product->discount_for_more = (int)$values['discount_for_more'];
        $product->easy_start = (boolean)$values['easy_start'];
        $product->easy_start_price = (int)$values['easy_start_price'];
        $product->easy_start_step = (int)$values['easy_start_step'];
        $product->not_discount = (boolean)$values['not_discount'];
        $product->save();

        //Insert translations
        $insertData = $this->getOnlyFullTranslations($requestData,'product_id', $product->id, ['description','composition']);
        ProductTranslations::query()->where('product_id',$product->id)->delete();
        ProductTranslations::query()->insert($insertData);

        //Update images
        if (count($values['product_images']) > 0){
            foreach ($values['product_images'] as $image_id => $image){
                $has_image = ProductImages::query()->find($image_id);

                if (is_null($has_image)){
                    $image_path = time() . $image->getClientOriginalName();
                    $image->move('main/products',$image_path);
                    ProductImages::query()->create([
                        'product_id' => $product->id,
                        'image' => $image_path
                    ]);
                } else{
                    @unlink(public_path('main/products/' . $has_image->image));
                    $image_path = time() . $image->getClientOriginalName();
                    $image->move('main/products',$image_path);
                    $has_image->update(['image' => $image_path]);
                }
            }
        }

        //Update statuses
        if(count($values['statuses']) > 0){
            $insertStatuses = [];
            foreach ($values['statuses'] as $status_id){
                array_push($insertStatuses,[
                    'product_id' => $product->id,
                    'status_id' => $status_id
                ]);
            }
            ProductStatuses::query()->where('product_id',$product->id)->delete();
            ProductStatuses::query()->insert($insertStatuses);
        }

        return redirect(route('locale.admin.product.index',$locale))->with('sweet_alert', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $locale
     * @param int $id
     *
     * @return RedirectResponse|Redirector
     * @throws Exception
     */
    public function destroy($locale, $id)
    {
        $product = Product::query()->findOrFail($id);

        $product->delete();

        return redirect(route('locale.admin.product.index',$locale))->with('sweet_alert', 'deleted');
    }

resources/views/main/products/product.blade.php
@extends('layouts.main')

@section('title') {{ $product->translate('title') }} @endsection

@section('style')
    <!-- Slider css -->
    <link href="{{ asset('main/assets/slick-carousel/slick.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('main/assets/slick-carousel/slick-theme.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Ninja-slider -->
    <link href="{{ asset('main/assets/ninja-slider/ninja-slider.css') }}" rel="stylesheet" type="text/css" />
    <script src="{{ asset('main/assets/ninja-slider/ninja-slider.js') }}" type="text/javascript"></script>
@endsection

@section('content')
    <main class="container text-center my-2 my-md-5">
        <div class="row my-4">
            <div class="col-md-5 ninja-slider-part">
                <div id="ninja-slider" class="bg-white p-0">
                    <div class="ninja-slider-content">
                        <div class="slider-inner">
                            <ul>
                                @if (count($product->images) > 0)
                                    @foreach($product->images as $key => $product_image)
                                        <li>
                                            <a class="ns-img" href="{{ asset('main/products/' . $product_image->image) }}"></a>
                                        </li>
                                    @endforeach
                                @else
                                    <li>
                                        <a class="ns-img" href="{{ $product->topImage() }}"></a>
                                    </li>
                                @endif
                            </ul>
                            <div class="fs-icon" title="Expand/Close"></div>
                        </div>
                        <div id="thumbnail-slider">
                            <div class="inner">
                                <ul>
                                    @if (count($product->images) > 0)
                                        @foreach($product->images as $key => $product_image)
                                            <li>
                                                <a class="thumb" href="{{ asset('main/products/' . $product_image->image) }}"></a>
                                                <span>{{ $key + 1 }}</span>
                                            </li>
                                        @endforeach
                                    @else
                                        <li>
                                            <a class="thumb" href="{{ $product->topImage() }}"></a>
                                            <span>{{ 1 }}</span>
                                        </li>
                                    @endif
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="product-item col-md-7 text-left pl-md-5">
                <div class="params d-none">
                    <span class="real-id">{{ $product->id }}</span>
                    <span class="real-price">{{ $product->price }}</span>
                    <span class="real-discount">{{ $product->discount }}</span>
                    <span class="real-discount-for-more">{{ $product->discount_for_more }}</span>
                    <span class="real-easy-start">{{ $product->easy_start }}</span>
                    <span class="real-easy-start-step">{{ $product->easy_start_step }}</span>
                    <span class="real-easy-start-price">{{ $product->easy_start_price }}</span>
                </div>

                <h3>{{ $product->translate('title') }}</h3>
                <p>@lang('main.articul') <b>{{ $product->articul }}</b></p>

                <p class="product-price-area @if(!$product->doublePrices(1)) d-none @endif text-muted mb-0">
                    <del>
                        <span class="product-price">{{ $product->price(1) }}</span>
                        @lang('main.dram')
                    </del>
                </p>
                <span class="text-pink font-size-md-25">
                    <span class="product-discount">{{ $product->discount(1) }}</span>
                    @lang('main.dram')
                </span>

                <div class="num-counter mt-4">
                    <button class="product-count-change" data-type="minus"><i class="fas fa-minus"></i></button>
                    <input readonly class="product-count" type="text" value="1">
                    <button class="product-count-change" data-type="plus"><i class="fas fa-plus"></i></button>
                    <br><br>
                    <a class="product-to-basket btn bg-pink text-white" role="button" style="cursor: pointer">@lang('main.to_basket')</a>
                </div>
            </div>

            <div class="col-12 second-modal mt-4 mt-md-5">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link text-pink active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
                           aria-selected="true">@lang('main.description')</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-pink" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
                           aria-selected="false">@lang('main.composition')</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-pink" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
                           aria-selected="false">@lang('main.reviews')</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="p-2 tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        {!! $product->translate('description') !!}
                    </div>
                    <div class="p-2 tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        {!! $product->translate('composition') !!}
                    </div>
                    <div class="p-2 tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                        {!! $product->translate('reviews') !!}
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

@section('script_end')
    <script src="{{ asset('main/custom/js/Pages/product.js') }}"></script>
@endsection

resources/views/main/products/statuses.blade.php
@extends('layouts.main')

@section('title') @lang('main.' . $status['prefix']) @endsection

@section('content')
    <main class="container text-center my-2 my-md-5">
        <h4 class="bg-pink text-uppercase text-white d-md-inline-block rounded py-1 px-3 my-4 my-md-0">@lang('main.' . $status['prefix'])</h4>
        @if(count($products) > 0)
            <div class="row new-item-section my-4">
                @foreach($products as $product)
                    <div class="product-item col-12 col-sm-6 col-lg-3 my-4">
                        <div class="media flex-column flex-md-row text-left">
                            <img class="img-fluid mr-2 mr-md-4" width="80" src="{{ $product->topImage() }}" alt="{{ $product->translate('title') }}" title="{{ $product->translate('title') }}">
                            <div class="media-body">
                                <div class="params d-none">
                                    <span class="real-id">{{ $product->id }}</span>
                                    <span class="real-price">{{ $product->price }}</span>
                                    <span class="real-discount">{{ $product->discount }}</span>
                                    <span class="real-discount-for-more">{{ $product->discount_for_more }}</span>
                                    <span class="real-easy-start">{{ $product->easy_start }}</span>
                                    <span class="real-easy-start-step">{{ $product->easy_start_step }}</span>
                                    <span class="real-easy-start-price">{{ $product->easy_start_price }}</span>
                                </div>
                                <a class="product-title text-dark" href="{{ route('locale.product', ['locale' => $locale['prefix'], 'articul__id' => $product->articul . '__' . $product->id]) }}">
                                    <h6 class="mt-0">{{ $product->translate('title') }}</h6>
                                </a>
                                <p class="product-price-area @if(!$product->doublePrices(1)) d-none @endif font-size-12 text-muted text-nowrap m-0">
                                    <del>
                                        <span class="product-price">{{ $product->price(1) }}</span> @lang('main.dram')
                                    </del>
                                    @lang('main.normal_price')
                                </p>
                                <span class="font-weight-bold text-pink font-size-sm-22">
                                    <span class="product-discount">{{ $product->discount(1) }}</span> @lang('main.dram')
                                </span>
                                <div class="num-counter text-left my-3 @if(!$product->doublePrices(1)) m-top-34 @endif">
                                    <button class="product-count-change" data-type="minus"><i class="fas fa-minus"></i></button>
                                    <input readonly class="product-count" type="text" value="1">
                                    <button class="product-count-change" data-type="plus"><i class="fas fa-plus"></i></button>
                                </div>
                                <a class="product-to-basket btn bg-pink text-white" role="button" style="cursor: pointer">@lang('main.to_basket')</a>
                            </div>
                        </div>
                    </div>
                @endforeach

                <div class="col-12 mt-4">
                    @include('main.extensions.pagination', ['data' => $products])
                </div>
            </div>
        @else
            <p class="text-center w-100 mt-3">@lang('main.products_empty_data')</p>
        @endif
    </main>
@endsection

@section('script_end')
    <script src="{{ asset('main/custom/js/Pages/products.js') }}"></script>
@endsection